### PR TITLE
Allow overlaying predicted mask onto the original image

### PR DESCRIPTION
**Pull request by frk2**
First of all THANK YOU FOR THIS! 

This really helps visualize how effective the network is during / after training so you get output like the following

c_af962335-00000000

### CODE REVIEW

**Comment by sacmehta** [comment]
You can do it easily as shown below. Let me know if it makes sense and then I can merge it.

#change 1 (after line 70)
img_orig = copy.deepcopy(img)

#change 2 (after line 101)
if args.colored:
            classMap_numpy_color = PILImage.fromarray(classMap_numpy)
            classMap_numpy_color.putpalette(pallete)
            classMap_numpy_color.save(args.savedir + os.sep + 'c_' + name.replace(args.img_extn, 'png'))
            if args.overlay:
            	classMap_numpy_color = numpy.array(classMap_numpy_color)
            	overlayed = cv2.addWeighted(img_orig, 0.5, classMap_numpy_color, 0.5,0)
            	cv2.imwrite(args.savedir + os.sep + 'over_' + name.replace(args.img_extn, 'jpg'), overlayed)

**Comment by frk2** [comment]
I'm cool with anything if it produces the above image :laughing: 

1. img_orig will still need to be resized if the input images are of diff sizes
2. Unclear how addWeighted works - classMap_numpy_color has a lot of black pixels in it (undetected region)

**Comment by sacmehta** [comment]
I have added an overlay option which will produce an output similar to below image. Please have a look. Sorry for late response.

over_frankfurt_000000_000576_leftimg8bit

**Comment by frk2** [comment]
Nice. Thanks 🙇

**Pull request closed without merging**
